// Code generated by mockery v1.0.0. DO NOT EDIT.

package iec

import mock "github.com/stretchr/testify/mock"

// MockIECManager is an autogenerated mock type for the IECManager type
type MockIECManager struct {
	mock.Mock
}

// GetClusterID provides a mock function with given fields:
func (_m *MockIECManager) GetClusterID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetNodeGroups provides a mock function with given fields:
func (_m *MockIECManager) GetNodeGroups() []*NodeGroup {
	ret := _m.Called()

	var r0 []*NodeGroup
	if rf, ok := ret.Get(0).(func() []*NodeGroup); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*NodeGroup)
		}
	}

	return r0
}

// Refresh provides a mock function with given fields:
func (_m *MockIECManager) Refresh() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
