{{- if .Values.local -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "autoscaler.name" . }}"
  namespace: kube-system
  labels:
    {{- include "autoscaler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "autoscaler.name" . }}"
subjects:
  - kind: ServiceAccount
    name: {{ include "autoscaler.name" . }}
    namespace: kube-system
{{- end }}